version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - tasknet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/tasks"]
      interval: 5s
      timeout: 2s
      retries: 50

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
    - "8081:80"
      
  db:
    image: postgres:15-alpine
    environment:
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - tasknet

  client:
    build: ./client
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - tasknet
    

volumes:
  db_data:

networks:
  tasknet: