version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
    secrets:
      - db_password
    command: >
      sh -c "export DB_PASSWORD=$(cat /run/secrets/db_password) && exec ./server"
    networks:
      - tasknet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/tasks"]
      interval: 5s
      timeout: 2s
      retries: 50

  proxy:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/reverse-proxy.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - tasknet
  db:
    image: postgres:15-alpine
    environment:
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_USER: ${POSTGRES_USER}
    secrets:
      - db_password
    command: >
      sh -c "export POSTGRES_PASSWORD=$(cat /run/secrets/db_password) && exec docker-entrypoint.sh postgres"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - tasknet

  client:
    build: ./client
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - tasknet
    

volumes:
  db_data:

networks:
  tasknet:

secrets:
  db_password:
    file: ./secrets/db_password.txt